"""
config.py — single source of truth for every path the Claude Migration Tool uses.

Per the build instructions, all Windows paths live here so they can be changed in one
place. Where the spec's documented path differs from what actually exists on real
machines, this module checks BOTH locations (verified real path first, spec path as a
fallback) so the tool works on the standalone-installer build *and* the Microsoft Store
build of Claude Desktop. See resolve_* helpers and the *_CANDIDATES lists.

Empirically verified discrepancies handled here:
  - Claude Code global config is ~/.claude.json (user-profile root), NOT ~/.claude/claude.json.
  - Cowork VM disks live under %APPDATA%\\Claude\\vm_bundles (installer build), NOT only
    %LOCALAPPDATA%\\Packages\\Claude_* (Store build).
"""

from __future__ import annotations

import os
import shutil
from datetime import datetime
from pathlib import Path

GENERATED_HEADER = "<!-- Auto-generated by Claude Migration Tool v1.0 — Review before use -->\n"

# --------------------------------------------------------------------------- logging
# The spec mandates migration.log and uses log("LEVEL", msg) across modules but lists no
# logger file. config.py is imported everywhere, so the shared logger lives here.
LOG_FILE = Path.cwd() / "migration.log"
_VALID_LEVELS = {"INFO", "WARN", "ERROR"}


def timestamp() -> str:
    """Filesystem-safe timestamp, e.g. 20260615-102341."""
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def log(level: str, message: str) -> None:
    """
    Append a line to migration.log. Levels: INFO, WARN, ERROR.
    Never pass secret values to this function (callers must redact first).
    """
    lvl = level.upper() if level.upper() in _VALID_LEVELS else "INFO"
    line = f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] [{lvl}] {message}"
    try:
        with open(LOG_FILE, "a", encoding="utf-8") as fh:
            fh.write(line + "\n")
    except OSError:
        pass  # logging must never crash the run


def safe_write(path: Path, content: str) -> bool:
    """
    Write text to *path*, backing up any existing file to {name}.backup.{timestamp} first.
    Verifies the write by reading back. Returns True on success. Never raises.
    """
    path = Path(path)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists():
            backup = path.parent / f"{path.name}.backup.{timestamp()}"
            shutil.copy2(path, backup)
            log("INFO", f"Backed up existing file to {backup}")
        path.write_text(content, encoding="utf-8")
        if path.exists():
            log("INFO", f"Written: {path}")
            return True
        log("ERROR", f"Write verification failed: {path}")
        return False
    except OSError as e:
        log("ERROR", f"Could not write {path}: {e}")
        return False


# --------------------------------------------------------------------------- roots
APPDATA = Path(os.environ.get("APPDATA", ""))
LOCALAPPDATA = Path(os.environ.get("LOCALAPPDATA", ""))
USERPROFILE = Path(os.environ.get("USERPROFILE", ""))

TOOL_VERSION = "1.0"


# --------------------------------------------------------------------------- helpers
def first_existing(candidates: list[Path]) -> Path | None:
    """Return the first path in *candidates* that exists, else None."""
    for c in candidates:
        try:
            if c and Path(c).exists():
                return Path(c)
        except OSError:
            continue
    return None


def glob_dirs(parent: Path, pattern: str) -> list[Path]:
    """Return immediate child directories of *parent* matching *pattern* (safe if absent)."""
    try:
        if parent and parent.exists():
            return sorted(p for p in parent.glob(pattern) if p.is_dir())
    except OSError:
        pass
    return []


def glob_files(parent: Path, pattern: str) -> list[Path]:
    """Return files under *parent* matching *pattern* recursively (safe if absent)."""
    try:
        if parent and parent.exists():
            return sorted(p for p in parent.rglob(pattern) if p.is_file())
    except OSError:
        pass
    return []


# --------------------------------------------------------------------------- candidate lists
# Claude Code global config: real path first, spec path second.
CLAUDE_CODE_GLOBAL_CANDIDATES = [
    USERPROFILE / ".claude.json",            # verified real location
    USERPROFILE / ".claude" / "claude.json",  # spec's documented location (fallback)
]

# Claude Desktop install location: installer build, alt installer path, then Store stub.
CLAUDE_DESKTOP_INSTALL_CANDIDATES = [
    LOCALAPPDATA / "AnthropicClaude",                 # standalone installer (spec)
    LOCALAPPDATA / "Programs" / "claude",             # alt installer layout
    APPDATA / "Claude",                               # app data dir (proxy: present => installed)
]

# Cowork VM virtual disks: installer build (Roaming\Claude\vm_bundles) + Store build (Packages).
COWORK_VHDX_PARENTS = [
    APPDATA / "Claude" / "vm_bundles",   # verified real location (installer build)
    LOCALAPPDATA / "Packages",           # Store build (glob Claude_* below)
]

# Cowork session/package parents (Store build keeps these under Packages\Claude_*).
COWORK_PACKAGE_PARENTS = [
    LOCALAPPDATA / "Packages",
]


def resolve_global_config() -> Path:
    """The Claude Code global config path that actually exists, or the preferred default."""
    return first_existing(CLAUDE_CODE_GLOBAL_CANDIDATES) or CLAUDE_CODE_GLOBAL_CANDIDATES[0]


def resolve_desktop_install() -> Path | None:
    """The Claude Desktop install/app-data path that exists, or None if not found."""
    return first_existing(CLAUDE_DESKTOP_INSTALL_CANDIDATES)


def resolve_cowork_vhdx() -> list[Path]:
    """All Cowork VM .vhdx files found across known locations (located, never copied)."""
    found: list[Path] = []
    # Installer build: AppData\Claude\vm_bundles\**\*.vhdx
    found += glob_files(APPDATA / "Claude" / "vm_bundles", "*.vhdx")
    # Store build: Packages\Claude_*\LocalState\**\*.vhdx (shallow into each package's LocalState)
    for pkg in glob_dirs(LOCALAPPDATA / "Packages", "*Claude*"):
        found += glob_files(pkg / "LocalState", "*.vhdx")
    # de-duplicate, preserve order
    seen: set[str] = set()
    unique: list[Path] = []
    for p in found:
        key = str(p).lower()
        if key not in seen:
            seen.add(key)
            unique.append(p)
    return unique


def resolve_cowork_packages() -> list[Path]:
    """Claude_* package folders under LocalAppData\\Packages (Store build), names only."""
    pkgs: list[Path] = []
    for parent in COWORK_PACKAGE_PARENTS:
        pkgs += glob_dirs(parent, "*Claude*")
    return pkgs


# --------------------------------------------------------------------------- source paths
# Primary map used by the analyser. claude_code_global is resolved to the real location.
SOURCE_PATHS = {
    "claude_desktop_config": APPDATA / "Claude" / "claude_desktop_config.json",
    "claude_appdata_folder": APPDATA / "Claude",
    "claude_code_global": resolve_global_config(),
    "claude_root": USERPROFILE / ".claude",
    "agents_folder": USERPROFILE / ".claude" / "agents",
    "plugins_folder": USERPROFILE / ".claude" / "plugins",
    "commands_folder": USERPROFILE / ".claude" / "commands",
    "projects_folder": USERPROFILE / ".claude" / "projects",
    "root_claude_md": USERPROFILE / ".claude" / "CLAUDE.md",
    "style_guide": USERPROFILE / ".claude" / "style-guide.md",
    "cowork_sessions": LOCALAPPDATA / "Packages",   # glob Claude_* via resolve_cowork_packages()
    "cowork_vhdx": APPDATA / "Claude" / "vm_bundles",  # see resolve_cowork_vhdx() for full search
}

# Claude Desktop installed location check (preflight uses resolve_desktop_install()).
CLAUDE_DESKTOP_INSTALL = CLAUDE_DESKTOP_INSTALL_CANDIDATES[0]

# Claude process name (for running-process check).
CLAUDE_PROCESS_NAME = "claude.exe"

# Files that must NEVER be copied (security).
NEVER_COPY_PATTERNS = [
    "*.key", "*.pem", "*.env", ".env*", "secrets.*",
    "credentials.json", ".credentials.json", "token.json", "*.token",
]

# Env variable keys that signal a token is present.
SECRET_ENV_KEY_PATTERNS = [
    "TOKEN", "KEY", "SECRET", "PASSWORD", "PASS",
    "AUTH", "CREDENTIAL", "API",
]

# Standard scaffold output paths (under ~/.claude).
CLAUDE_ROOT = USERPROFILE / ".claude"
OUTPUT_PATHS = {
    "root_claude_md": CLAUDE_ROOT / "CLAUDE.md",
    "style_guide": CLAUDE_ROOT / "style-guide.md",
    "connectors_todo": CLAUDE_ROOT / "connectors-todo.md",
    "migration_report": CLAUDE_ROOT / "MIGRATION-REPORT.md",
    "projects_folder": CLAUDE_ROOT / "projects",
}

# Active-vs-abandoned project threshold.
ACTIVE_PROJECT_DAYS = 90

# Writing-style keywords (used by pillar scoring and style extraction).
STYLE_KEYWORDS = [
    "tone", "voice", "style", "format", "prefer", "avoid", "always", "never",
    "formal", "casual", "concise", "detailed", "bullet", "prose", "table",
]
